# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'RCSceneExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RCSceneExample
  
  pod 'RCSceneRoom/RCSceneRoom', :path => '../'
  pod 'RCSceneRoom/RCSceneGift', :path => '../'
  pod 'RCSceneRoom/RCSceneMusic', :path => '../'
  pod 'RCSceneRoom/RCSceneAnalytics', :path => '../'
  pod 'RCSceneRoom/RCSceneRoomSetting', :path => '../'
  
end
